### ISSUE TITLE
Connection issue

### ISSUE THREAD

**Issue by Phoedoth** [yallie/MdlpClient#19]
Добрый день. Где-то неделю назад перестал подключаться:

MdlpApiClient.MdlpException
  HResult=0x80131500
  Message=The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.
  Source=MdlpApiClient
  StackTrace:
   at MdlpApiClient.MdlpClient.ThrowOnFailure(IRestResponse response)
   at MdlpApiClient.MdlpClient.Execute[T](IRestRequest request, String apiMethodName)
   at MdlpApiClient.MdlpClient.Post[T](String url, Object body, Parameter[] parameters, String apiMethodName)
   at MdlpApiClient.MdlpClient.Authenticate(String clientId, String clientSecret, String userId, String authType)
   at MdlpApiClient.ResidentCredentials.Authenticate(MdlpClient apiClient)
   at MdlpApiClient.CredentialsAuthenticator.Authenticate(IRestClient client, IRestRequest request)
   at RestSharp.RestClient.Execute(IRestRequest request, String httpMethod, Func`3 getResponse)
   at RestSharp.RestClient.Execute(IRestRequest request)
   at RestSharp.RestClient.Execute[T](IRestRequest request)
   at MdlpApiClient.MdlpClient.Execute[T](IRestRequest request, String apiMethodName)
   at MdlpApiClient.MdlpClient.Post[T](String url, Object body, Parameter[] parameters, String apiMethodName)
   at MdlpApiClient.MdlpClient.Authenticate(String clientId, String clientSecret, String userId, String authType)
   at MdlpApiClient.ResidentCredentials.Authenticate(MdlpClient apiClient)
   at MdlpConnect.Program.Main(String[] args) in \MdlpConnect\MdlpConnect\Program.cs:line 25

Inner Exception 1:
WebException: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.

Inner Exception 2:
AuthenticationException: The remote certificate is invalid according to the validation procedure.

Сертификат в порядке. Подключение к вэб-версии через него работает. Буду признателен за любые идеи

**Comment by Phoedoth** [comment]
Пардон, не заметил что сертификат теперь другой корневой.
